/// Runtime support library for code generated by tsxtoflutter.
///
/// Spacing scale, design-token ThemeExtension, responsive helpers, and the
/// adaptive widget shim layer (`AppButton`, `AppSwitch`, `AppScaffold`).
library;

export 'src/breakpoints.dart';
export 'src/spacing.dart';
export 'src/tokens.dart';
export 'src/adaptive/app_button.dart';
export 'src/adaptive/app_scaffold.dart';
export 'src/adaptive/app_switch.dart';
